[package]
name = "computing"
version = "0.1.0"
authors = ["nacho <sabauflorin28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.5.2"
bytemuck = "1.2.0"
shaderc = "0.6.2"
smol = "0.3.2"
